### PR TITLE
added clevertricks.sql to generate the initial tables

### PR DESCRIPTION
**Pull request by arnaud-blanc**

### CODE REVIEW

**Comment by floriane-cheneveau** [comment]
good :)

**Comment by ced37** [comment]
it's ok for me

**Review by floriane-cheneveau — DISMISSED** [review]

**Review by ced37 — DISMISSED** [review]

**Review by RomainClair — CHANGES_REQUESTED** [review]
The clevertricks.sql script seems invalid and can't be imported curing my test
It may be safer to dump an existing database rather than manually write the script

**Review by ced37 — APPROVED** [review]

**Review by ced37 — APPROVED** [review]

**Review by floriane-cheneveau — APPROVED** [review]

**Review by RomainClair — APPROVED** [review]
You probably should use the DROP TABLE IF EXISTS before creating tables so that your script will create the database OR reinitialize the database in case of an existing one

**Pull request merged**
